//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServicesSignosVitales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class expediente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public expediente()
        {
            this.sig_vit = new HashSet<sig_vit>();
        }
    
        public Nullable<int> Idpaciente { get; set; }
        public string Expediente1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sig_vit> sig_vit { get; set; }
        public virtual pacientes pacientes { get; set; }
    }
}
