//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServicesSignosVitales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fre_card
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fre_card()
        {
            this.detalles = new HashSet<detalles>();
        }
    
        public Nullable<int> IdSV { get; set; }
        public int IdFC { get; set; }
        public int Nivel_frecard { get; set; }
        public string Estado { get; set; }
        public System.DateTime Fecha_regfc { get; set; }
        public System.TimeSpan Hora_regfc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalles> detalles { get; set; }
        public virtual sig_vit sig_vit { get; set; }
    }
}
