//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServicesSignosVitales.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class uth_inte09Entities : DbContext
    {
        public uth_inte09Entities()
            : base("name=uth_inte09Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<detalles> detalles { get; set; }
        public virtual DbSet<expediente> expediente { get; set; }
        public virtual DbSet<fre_card> fre_card { get; set; }
        public virtual DbSet<pacientes> pacientes { get; set; }
        public virtual DbSet<peso> peso { get; set; }
        public virtual DbSet<pres_arte> pres_arte { get; set; }
        public virtual DbSet<sat_oxi> sat_oxi { get; set; }
        public virtual DbSet<sig_vit> sig_vit { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<talla> talla { get; set; }
        public virtual DbSet<tem_cor> tem_cor { get; set; }
    }
}
